### ISSUE TITLE
Improved completion with multiple parameters

### ISSUE THREAD

**Issue by latenitecali** [snowkit/sublime_haxe#1]
Suggestion. It would be nice if the second, third, etc parameters were shown after the first drop down list goes away. 

Example: If I type
spriteColor = new ColorHSV(
I get a drop down with the 4 parameters ColorHSV() takes. After typing the value for hue, the other parameters go away. I'm not sure how this could be done cleanly (I personally thing the inline way the other Haxe plugin works is a little obtrusive, but it works).

Can this same dropdown come up again, with the remaining parameters listed?

**Comment by ruby0x1** [comment]
It's planned but the way that works is definitely too intrusive, I constantly fought it (and when teaching people haxe it was a massive source of confusion). haxe completion doesn't give the remaining arguments unfortunately, so its just a matter of finding an elegant way of coding it in. 

I figured I would wait and see how long before haxe 3.2 release phase comes along as there are quite a few new completion features that would be easier to do all the work at once, maybe.

**Comment by latenitecali** [comment]
Yeah the inline way was super confusing at first, but I got used to it. I love the drop down (even though you don't really select the items) because it's out of the way but informative. If it would continue with each parameter it would be perfect I think

**Comment by ruby0x1** [comment]
Yea, the other problem is that sublime completion is unforgiving on the insertion, if you enter a `""` as in "don't insert anything" it takes that as "insert the visible text" which makes a mess, so I had to temporarily put " " to get it not to be really annoying, and then it doesn't even handle the ( opening bracket nicely, so it has to be coded around with hacks basically - which is where the source of the other annoyances come from right now.

What I wanted was the insertion would just select the text (so its not in the way) and only for the current argument, and show the list like it does now. then on subsequent , it would show the remaining args. It will happen, though.

**Comment by ruby0x1** [comment]
For reference, the recent release of https://github.com/snowkit/sublime_flow solves the annoyances with inserting the issues, and https://github.com/snowkit/tides is in progress to bring us better parsing for the features like continuous argument completion. Since those are both tracked elsewhere, this issue will be closed.
